// routing/examples/react/src/pages/[...slug].tsx
import { useLocation, Link } from "react-router-dom";

export default function NotFound() {
    const location = useLocation();

    return (
        <div style={{ padding: '20px', color: 'red' }}>
            <h2>404 - Not Found</h2>
            <p>The path <code>{location.pathname}</code> does not exist.</p>
            <Link to="/">Go Home</Link>
        </div>
    );
}

// routing/examples/vue/src/pages/[...slug].vue
<script setup lang="ts">
import { useRoute, RouterLink } from 'vue-router'

const route = useRoute()
</script>

<template>
  <div style="padding: 20px; color: red;">
    <h2>404 - Not Found</h2>
    <p>The path <code>{{ route.path }}</code> does not exist.</p>
    <RouterLink to="/">Go Home</RouterLink>
  </div>
</template>
