// routing/examples/react/pages/(auth)/login.tsx
import { useNavigate } from "react-router-dom";

export default function LoginPage() {
    const navigate = useNavigate();

    return (
        <div>
            <h2>Login Page</h2>
            <p>This page is inside <code>pages/(auth)/login.tsx</code></p>
            <p>The URL is <code>/login</code> (group name omitted).</p>
            <button onClick={() => navigate('/dashboard')}>Login & Go to Dashboard</button>
        </div>
    );
}

// routing/examples/vue/src/pages/(auth)/login.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'

const router = useRouter()

function login() {
  router.push('/dashboard')
}
</script>

<template>
  <div>
    <h2>Login Page</h2>
    <p>This page is inside <code>pages/(auth)/login.vue</code></p>
    <p>The URL is <code>/login</code> (group name omitted).</p>
    <button @click="login">Login & Go to Dashboard</button>
  </div>
</template>
