// routing/examples/vue/src/pages/posts/page.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
const posts = [1, 2, 3]
</script>

<template>
  <div>
    <h2>Posts List</h2>
    <ul>
      <li v-for="id in posts" :key="id">
        <RouterLink :to="`/posts/${id}`">View Post {{ id }}</RouterLink>
      </li>
    </ul>
  </div>
</template>

// routing/examples/react/pages/posts/page.tsx
import { Link } from "react-router-dom";

export default function PostsIndex() {
    const posts = [1, 2, 3];

    return (
        <div>
            <h2>Posts List</h2>
            <ul>
                {posts.map(id => (
                    <li key={id}>
                        <Link to={`/posts/${id}`}>View Post {id}</Link>
                    </li>
                ))}
            </ul>
        </div>
    );
}
