// routing/examples/vue/pages/page.vue
<template>
  <div>
    <h2>Home Page</h2>
    <p>Welcome to the enhanced routing example.</p>
    <ul>
      <li><strong>Groups:</strong> <code>(auth)</code> folder is omitted from URL.</li>
      <li><strong>Nested Layouts:</strong> Dashboard has its own sidebar.</li>
      <li><strong>Dynamic Routes:</strong> Posts use <code>[id]</code>.</li>
      <li><strong>Catch-all:</strong> Unmatched routes fall back to <code>[...slug]</code>.</li>
    </ul>
  </div>
</template>

// routing/examples/react/src/pages/index.tsx
export default function HomePage() {
    return (
        <div>
            <h2>Home Page</h2>
            <p>Welcome to the enhanced routing example.</p>
            <ul>
                <li><strong>Groups:</strong> <code>(auth)</code> folder is omitted from URL.</li>
                <li><strong>Nested Layouts:</strong> Dashboard has its own sidebar.</li>
                <li><strong>Dynamic Routes:</strong> Posts use <code>[id]</code>.</li>
                <li><strong>Catch-all:</strong> Unmatched routes fall back to <code>[...slug]</code>.</li>
            </ul>
        </div>
    );
}
